sudo: required

services:
  - docker

before_install:
  - docker pull squidfunk/mkdocs-material:4.6.3
  - mkdir -p site

script:
  - docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material:4.6.3 build
  - echo "xqemu.com" > site/CNAME

deploy:
  provider: pages
  local-dir: site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
